[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-cache-dependencies"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "@netlify/plugin-image-optim"
